name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |          
          docker build -t saidsmajicwork/simple-web-app:latest /Users/said.smajic/Desktop/simple_app_deployment/Application
